### PR TITLE
fix: gracefully handle number prefixed names

### LINKED ISSUE #435: [BUG] cli crashes when using numeric prefixed names
## Description

When using `hc scaffold web-app` with a name that starts with numbers and contains underscores (e.g., 03_to_04), the scaffolding process crashes during DNA generation and build. Similar behaviour can also be reproduced when scaffolding an `entry-type` also containing a numeric prefixed names.

## Expected behavior

Successful scaffolding of a web app or entry-type

### PR DESCRIPTION
**Pull request by c12i**
Fixes #435

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -167,17 +167,27 @@ pub fn check_case(input: &str, identifier: &str, case: Case) -> ScaffoldResult<(
             "{identifier} must be {case:?} Case",
         )));
     }
+    if input.chars().next().map_or(false, char::is_numeric) {
+        return Err(ScaffoldError::InvalidStringFormat(format!(
+            "{identifier} must not start with a numeric"
```
Comment (ThetaSinner) [inline src/utils.rs:172]:
```suggestion
            "{identifier} must not start with a number"
```

Or maybe "numeric value"?

**Review by ThetaSinner — APPROVED** [review]
Nice, thanks for fixing this :)
