### PR TITLE
fix(svelte): Ensure client is loaded before use

### LINKED ISSUE #466: [FIX] Improve client loading for svelte template
A follow up issue to #425 to add more measures to ensure the client can be safely accessed from child components of the web app with better handling of errored and loading states

### PR DESCRIPTION
**Pull request by c12i**
Closes #466 

This PR adds measures to ensure the client is not accessible before its initialized. This is achieved by moving the client state to a global state and and sharing it across child components.

**Blocked by failing CI**

### CODE REVIEW

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs [hunk 1]
```diff
@@ -1,7 +1,83 @@
...
+
+  const { subscribe, set, update } = store;
+
+  return {
+    subscribe,
+    connect: async () => {
+      update(s => ({ ...s, loading: true }));
+      try {
+        {{#if holo_enabled}}
+        if (IS_HOLO) {
```
Comment (jost-s) [inline templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs:36]: Do we still need to keep supporting Holo architecture?

**Review by jost-s — COMMENTED** [review]
Lexically LGTM. Can I test this somehow or even better, is this tested on CI somehow? If not, can it be?

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs (hunk 1 above)
Comment (c12i) [reply templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs:36]: I am not sure, the most up to date version of the holo web sdk seems to use [`v0.18.0-dev.2`](https://github.com/Holo-Host/web-sdk/blob/develop/package.json#L51C28-L51C40) of the js client, supporting the 0.4 line. Updates to the lib have since stopped though.

I can bring this up as a topic in the weekly meeting.

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs [hunk 2]
```diff
@@ -1,7 +1,83 @@
-import { type AppClient } from "@holochain/client";
+import { writable, type Writable } from 'svelte/store';
```
Comment (mattyg) [inline templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs:1]: Missing the import of `get` from `svelte/store`;

Comment (mattyg) [inline templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs:1]: `type Writable` is not used

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs [hunk 3]
```diff
@@ -1,7 +1,83 @@
...
+import { getContext, setContext } from 'svelte';
```
Comment (mattyg) [inline templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs:2]:
```suggestion
import { getContext } from 'svelte';
```
setContext is not used

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs (hunk 2 above)
Comment (mattyg) [inline templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs:1]:
```suggestion
import { get, writable } from 'svelte/store';
```
`type Writable` not used, `get` missing

File: templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs [hunk 4]
```diff
@@ -1,71 +1,78 @@
...
-  ActionHash,
-  Link,
-  AppClient,
-  NewEntryAction,
-  HolochainError,
-} from '@holochain/client';
-import { type ClientContext, clientContext } from '../../contexts';
+import { onMount } from 'svelte';
+import type { EntryHash, Record, AgentPubKey, ActionHash, Link, NewEntryAction, HolochainError } from '@holochain/client';
+import { SignalType } from '@holochain/client';
```
Comment (mattyg) [inline templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs:4]: `SignalType` was removed from holochain-client-js due to changes in enum serialization: see https://github.com/holochain/holochain-client-js/pull/322/files#

**Comment by mattyg** [comment]
I'm running into a few unrelated issues that are preventing me from testing this:
- When I run `npm run start`, I get an error from hc-spin that the request to issue an app auth token timed out:
```
[1] (node:976325) UnhandledPromiseRejectionWarning: Error: Request timed out in 60000 ms: issue_app_authentication_token
[1]     at Timeout.<anonymous> (/home/matt/Projects/Holochain/forum/node_modules/@holochain/hc-spin/dist/main/index.js:4576:34)
[1]     at listOnTimeout (node:internal/timers:573:17)
[1]     at process.processTimers (node:internal/timers:514:7)
[1] (Use `electron --trace-warnings ...` to show where the warning was created)
[1] (node:976325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
- When I run `npm run start:tauri`, I get an error that the conductor config is invalid:
```
[1] [1] 2025-03-04T23:30:50.857592Z  WARN kitsune_p2p::spawn: crates/kitsune_p2p/kitsune_p2p/src/spawn.rs:31: gossip_arc_clamping network tuning parameter is not set. This is not permitted without "unstable-sharding" feature enabled. Please choose either "empty" or "full"
[1] [1] 2025-03-04T23:30:50.857671Z ERROR holochain::conductor::conductor::builder: crates/holochain/src/conductor/conductor/builder.rs:275: Error spawning networking err=OtherKitsuneP2pError(Other(OtherError("gossip_arc_clamping must be set")))
```

I'll make issues in the corresponding repos. Have you been able to run this @c12i?

File: templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs (hunk 4 above)
Comment (c12i) [reply templates/ui-frameworks/svelte/collection/ui/src/{{dna_role_name}}/{{coordinator_zome_manifest.name}}/{{pascal_case collection_name}}.svelte.hbs]: Removed, this was a left over change while fixing merge conflicts

**Comment by c12i** [comment]
> I'll make issues in the corresponding repos.

Feel free to open, I suspect the error might be related to the change in enum serialization as well. Last manual testing was done on `dev.18` and things were working then.

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs (hunk 3 above)
Comment (c12i) [reply templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs]: Removed, thanks

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs (hunk 2 above)
Comment (c12i) [reply templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs]: Fixed, thanks

File: templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs (hunk 1 above)
Comment (jost-s) [reply templates/ui-frameworks/svelte/web-app/ui/src/contexts.ts.hbs:36]: Yes, please do!

**Review by jost-s — APPROVED** [review]
Tested with success

> [0]   VITE v5.4.14  ready in 329 ms
